version: '3.8'

services:
  postgresql:
    container_name: postgresql-finalProject
    image: postgres:latest
    environment:
      POSTGRES_USER: project
      POSTGRES_PASSWORD: project
      POSTGRES_DB: final_project
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  flask_backend:
    container_name: flask-app
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - postgresql
    environment:
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_DATABASE=devops
      - DB_USER=devops
      - DB_PASSWORD=devops

  angular_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app/node_modules
    ports:
      - "4200:80"

volumes:
  postgresql-data:
