version: '3.8'

services:
  mysql:
    container_name: mysql-finalProject
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
      MYSQL_USER: devops
      MYSQL_PASSWORD: devops
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  flask_backend:
    container_name: flask-app
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=devops
      - MYSQL_USER=devops
      - MYSQL_PASSWORD=devops

  react_native_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "19000:19000"

volumes:
  mysql-data:
